/**
 * Plant profile constants — AUTO-GENERATED by tools/sync_remote_ui_profiles.py
 * Source: src/plants.cpp plant_names[PLANT_NUMS]
 * Do not edit manually; re-run the sync script after changing plants.cpp.
 */
(function (global) {
  'use strict';
  var PLANT_NUMS = 379;
  var STAGE_PRESET_SEEDLING = 376;
  var STAGE_PRESET_VEGETATIVE = 377;
  var STAGE_PRESET_FLOWERING = 378;

  function isStagePresetProfileId(profileId) {
    var id = Number(profileId);
    return Number.isFinite(id) && (
      id === STAGE_PRESET_SEEDLING ||
      id === STAGE_PRESET_VEGETATIVE ||
      id === STAGE_PRESET_FLOWERING
    );
  }

  global.GH_PLANT_NUMS = PLANT_NUMS;
  global.GH_STAGE_PRESET_SEEDLING = STAGE_PRESET_SEEDLING;
  global.GH_STAGE_PRESET_VEGETATIVE = STAGE_PRESET_VEGETATIVE;
  global.GH_STAGE_PRESET_FLOWERING = STAGE_PRESET_FLOWERING;
  global.isStagePresetProfileId = isStagePresetProfileId;
})(typeof window !== 'undefined' ? window : globalThis);
